package View;


import Controller.ControllerAnzol;
import Dao.ProdutoDAO;
import Model.BdAnzol;
import Model.UniLotePeqException;
import Model.Anzol;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadAnzol extends javax.swing.JFrame {

    private static CadAnzol unicoCadAnzol;   
    private Anzol a1 = new Anzol();
    private static BdAnzol gp = new BdAnzol();

    public static CadAnzol getCadAnzol(BdAnzol gp1){
        gp = gp1;
        if(unicoCadAnzol == null){
            unicoCadAnzol = new CadAnzol();
        }
        return unicoCadAnzol;
    }
    private CadAnzol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAnzol = new javax.swing.JTable();
        jlCodigoLote = new javax.swing.JLabel();
        jlUnidadesLote = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlModelo = new javax.swing.JLabel();
        jlPreco = new javax.swing.JLabel();
        jlTamanho = new javax.swing.JLabel();
        jlUnidades = new javax.swing.JLabel();
        jtCodigoLote = new javax.swing.JTextField();
        jtUnidadesLote = new javax.swing.JTextField();
        jtMarca = new javax.swing.JTextField();
        jtModelo = new javax.swing.JTextField();
        jtPreco = new javax.swing.JTextField();
        jtTamanho = new javax.swing.JTextField();
        jtUnidadesPacote = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtMes = new javax.swing.JTextField();
        jtDia = new javax.swing.JTextField();
        jtAno = new javax.swing.JTextField();
        jlDia = new javax.swing.JLabel();
        jlAno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btCad = new javax.swing.JButton();
        jlInformacoes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRAR ANZOL");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tbAnzol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO LOTE", "UNIDADES LOTE", "MODELO"
            }
        ));
        tbAnzol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAnzolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAnzol);

        jlCodigoLote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlCodigoLote.setText("CÓDIGO LOTE");

        jlUnidadesLote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlUnidadesLote.setText("UNIDADES LOTE");

        jlMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlMarca.setText("MARCA");

        jlModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlModelo.setText("MODELO");

        jlPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlPreco.setText("PREÇO");

        jlTamanho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlTamanho.setText("TAMANHO");

        jlUnidades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlUnidades.setText("UNIDADES PACOTE");

        jtUnidadesLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUnidadesLoteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("FABRICAÇÃO:");

        jtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMesActionPerformed(evt);
            }
        });

        jlDia.setText("DIA");

        jlAno.setText("ANO");

        jLabel2.setText("MÊS");

        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCad.setText("CADASTRAR");
        btCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadActionPerformed(evt);
            }
        });

        jlInformacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlInformacoes.setText("INFORMAÇÕES:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlCodigoLote)
                            .addComponent(jlUnidadesLote)
                            .addComponent(jlTamanho)
                            .addComponent(jlMarca)
                            .addComponent(jlPreco)
                            .addComponent(jlUnidades)
                            .addComponent(jlModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtModelo)
                            .addComponent(jtPreco)
                            .addComponent(jtTamanho)
                            .addComponent(jtUnidadesPacote)
                            .addComponent(jtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtUnidadesLote)
                            .addComponent(jtMarca))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jlInformacoes)
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlDia)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel2)
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jlAno)))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlInformacoes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDia)
                            .addComponent(jlAno)
                            .addComponent(jLabel2))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCodigoLote)
                            .addComponent(jtCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlUnidadesLote)
                            .addComponent(jtUnidadesLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMarca)
                            .addComponent(jtMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlModelo)
                            .addComponent(jtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPreco)
                            .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTamanho)
                            .addComponent(jtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlUnidades)
                            .addComponent(jtUnidadesPacote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btLimpar)
                    .addComponent(btCad)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtUnidadesLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUnidadesLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUnidadesLoteActionPerformed

    private void jtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMesActionPerformed

    private void btCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadActionPerformed
        cadAnzol();
        listaTab();
    }//GEN-LAST:event_btCadActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void tbAnzolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAnzolMouseClicked
        selectTab();
    }//GEN-LAST:event_tbAnzolMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        listaTab();
    }//GEN-LAST:event_formWindowGainedFocus

    
    public void selectTab(){
        String valLinTab = "";
        int posLin = tbAnzol.getSelectedRow();
          
        
        for(int coluna = 0;coluna < tbAnzol.getColumnCount(); coluna++ ){
            valLinTab += tbAnzol.getModel().getValueAt(posLin,coluna).toString() + "\n";
            
            
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido: \n"+valLinTab,
                "Seleção na tabela",
                1
        );
    }
    
    public void listaTab(){
        DefaultTableModel modelo = (DefaultTableModel) tbAnzol.getModel();
        modelo.setNumRows(0);
        
        ControllerAnzol.carregaTabela(modelo);

    }
    
    public int cadAnzol(){
        a1 = new Anzol();
        a1.setCodigoLote(Integer.parseInt(jtCodigoLote.getText()));
        try{
            a1.setUnidadesLote(Integer.parseInt(jtUnidadesLote.getText()));
        }
        catch(UniLotePeqException upe){
            upe.impUniLotePeq();
            a1 = upe.corrigeUniLotePeq(a1);
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                    null,
                    "VALOR DA UNIDADES LOTE DEVE SER INTEIRO",
                    "Erro de Cadastro",
                    0
            );
            limpar();
        }
        a1.setMarca(jtMarca.getText());
        a1.setModelo(jtModelo.getText());
        a1.setPreco(Float.valueOf(jtPreco.getText()));
        a1.setTamanho(Integer.parseInt(jtTamanho.getText()));
        a1.setUnidadesPacote(Integer.parseInt(jtUnidadesPacote.getText()));
        a1.setFabri(jtDia.getText()+"/"+jtMes.getText()+"/"+jtAno.getText());
        
        boolean feed = ControllerAnzol.cadastrarAnzol(a1);
       
       if(feed){
                JOptionPane.showMessageDialog(
                    null,
                    "Produto cadastrada com sucesso!",
                    "Cadastro Ok",
                    1
                );
                limpar();
       }
       else{
                JOptionPane.showMessageDialog(
                    null,
                    "Já existe um produto com este código",
                    "Erro de Cadastro",
                    0
                );
                limpar();
       }
       return 0;
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja sair?",
                    "Saida",
                    JOptionPane.YES_NO_OPTION
                );
        if(resp == 0){
            dispose();
        }
        else{
            limpar();
        }
    }
    
    public void limpar(){
        jtCodigoLote.setText("");
        jtUnidadesLote.setText("");
        jtMarca.setText("");
        jtModelo.setText("");
        jtPreco.setText("");
        jtTamanho.setText("");
        jtUnidadesPacote.setText("");
        jtDia.setText("");
        jtMes.setText("");
        jtAno.setText("");
        jtCodigoLote.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAnzol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAnzol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAnzol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAnzol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAnzol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCad;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlCodigoLote;
    private javax.swing.JLabel jlDia;
    private javax.swing.JLabel jlInformacoes;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlTamanho;
    private javax.swing.JLabel jlUnidades;
    private javax.swing.JLabel jlUnidadesLote;
    private javax.swing.JTextField jtAno;
    private javax.swing.JTextField jtCodigoLote;
    private javax.swing.JTextField jtDia;
    private javax.swing.JTextField jtMarca;
    private javax.swing.JTextField jtMes;
    private javax.swing.JTextField jtModelo;
    private javax.swing.JTextField jtPreco;
    private javax.swing.JTextField jtTamanho;
    private javax.swing.JTextField jtUnidadesLote;
    private javax.swing.JTextField jtUnidadesPacote;
    private javax.swing.JTable tbAnzol;
    // End of variables declaration//GEN-END:variables
}
